name: Backup and Restore PostgreSQL

on:
  workflow_dispatch:  # Allows manual execution from GitHub UI

jobs:
  backup_restore:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d ${{ secrets.POSTGRES_DB }}"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ secrets.POSTGRES_USER }}; do
            echo "⏳ Waiting for PostgreSQL..."
            sleep 2
          done
          echo "✅ PostgreSQL is ready!"

      - name: Run Backup Script
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          BACKUP_DIR: backup
          MODE: backup
        run: python3 postgres_backup_restore.py

      - name: Upload backup files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: database-backup
          path: backup/
